#include "Processor.h"
#include <iostream>
#include <stdexcept>
#include <random>
void need(bool ok,const char* text){if(!ok)throw std::runtime_error(text);std::cout<<"PASS "<<text<<"\n";}
void needQuiet(bool ok,const char* text){if(!ok)throw std::runtime_error(text);}
void param(BundleProcessor& p,const char* id,float value){auto* a=p.apvts.getParameter(id);a->setValueNotifyingHost(a->convertTo0to1(value));}
std::vector<float> render(BundleProcessor& p,int frames,float frequency=225,float amplitude=.18f,int block=256){juce::MidiBuffer midi;juce::AudioBuffer<float> b(2,block);std::vector<float> output;output.reserve(size_t(frames));for(int n=0;n<frames;n+=block){int count=juce::jmin(block,frames-n);b.setSize(2,count,false,false,true);for(int j=0;j<count;++j){float t=float(n+j)/48000.f;float voiced=amplitude*(std::sin(juce::MathConstants<float>::twoPi*frequency*t)+.2f*std::sin(juce::MathConstants<float>::twoPi*frequency*3*t));b.setSample(0,j,voiced);b.setSample(1,j,voiced*.85f);}p.processBlock(b,midi);for(int j=0;j<count;++j){float x=b.getSample(0,j);needQuiet(std::isfinite(x)&&std::abs(x)<8,"Audio invalid");output.push_back(x);}}return output;}
double rms(const std::vector<float>& x){double e=0;size_t start=x.size()/2;for(size_t i=start;i<x.size();++i)e+=double(x[i])*x[i];return std::sqrt(e/double(x.size()-start));}
int main(int argc,char** argv){try{juce::ScopedJuceInitialiser_GUI gui;const juce::String directory=argc>1?argv[1]:"previews";juce::File out=juce::File::getCurrentWorkingDirectory().getChildFile(directory);out.createDirectory();
 for(int k=0;k<7;++k){BundleProcessor p(k);need(p.getNumPrograms()==(k==1?11:7),"Six presets plus Default per plugin");p.prepareToPlay(48000,256);auto normal=render(p,24000);need(rms(normal)>.0001,"Plugin outputs voiced audio");
  for(int preset=1;preset<p.getNumPrograms();++preset){p.setCurrentProgram(preset);p.prepareToPlay(48000,256);auto result=render(p,16384);need(rms(result)>.00001,"Preset produces finite audible output");}
  p.setCurrentProgram(3);juce::MemoryBlock state;p.getStateInformation(state);BundleProcessor copy(k);copy.setStateInformation(state.getData(),int(state.getSize()));need(copy.getCurrentProgram()==3 && copy.values()==p.values(),"Preset and all parameters round-trip");BundleProcessor foreign((k+1)%7);auto original=foreign.values();foreign.setStateInformation(state.getData(),int(state.getSize()));need(foreign.values()==original,"Foreign plugin state rejected");
  p.setCurrentProgram(0);param(p,"bypass",1);p.prepareToPlay(48000,256);auto bypass=render(p,16384);const int latency=p.getLatencySamples();double error=0;for(size_t i=size_t(latency+512);i<bypass.size();++i){float t=float(int(i)-latency)/48000.f;float ref=.18f*(std::sin(juce::MathConstants<float>::twoPi*225*t)+.2f*std::sin(juce::MathConstants<float>::twoPi*675*t));error=juce::jmax(error,std::abs(double(bypass[i])-ref));}need(error<.00001,"Bypass matches original at reported latency");param(p,"bypass",0);
  p.prepareToPlay(48000,256);auto silent=render(p,8192,225,0);need(rms(silent)<1.e-8,"No generated sound without input");
  for(double sr:{44100.,96000.}){p.prepareToPlay(sr,127);auto result=render(p,2048);need(rms(result)>=0,"Sample-rate change and oversized host block safe");}p.setCurrentProgram(1);p.prepareToPlay(48000,256);render(p,k==6?192000:4096);
  std::unique_ptr<juce::AudioProcessorEditor> editor(p.createEditor());for(auto size:std::array<std::pair<int,int>,2>{{{660,360},{990,540}}}){editor->setSize(size.first,size.second);for(auto* c:editor->getChildren())if(c->isVisible())needQuiet(editor->getLocalBounds().contains(c->getBounds()),"UI child clipped");}
  editor->setSize(660,360);auto image=editor->createComponentSnapshot(editor->getLocalBounds());auto file=out.getChildFile(juce::String(p.product().slug)+".png");juce::FileOutputStream stream(file);juce::PNGImageFormat png;need(png.writeImageToStream(image,stream),"Real UI screenshot saved");
  std::cout<<"PLUGIN "<<p.getName()<<" latency "<<p.getLatencySamples()<<" samples\n";
 }
 // Full chain with a realistic synthetic voiced signal, not a duplicate of
 // any engine implementation. Check stereo/mono and finite peak behaviour.
 std::array<std::unique_ptr<BundleProcessor>,7> chain;for(int k=0;k<7;++k){chain[size_t(k)]=std::make_unique<BundleProcessor>(k);chain[size_t(k)]->prepareToPlay(48000,256);}juce::MidiBuffer midi;juce::AudioBuffer<float> b(2,256);double total=0;for(int block=0;block<160;++block){for(int j=0;j<256;++j){float t=float(block*256+j)/48000;float x=.12f*(std::sin(juce::MathConstants<float>::twoPi*170*t)+.3f*std::sin(juce::MathConstants<float>::twoPi*510*t));b.setSample(0,j,x);b.setSample(1,j,x);}for(auto& p:chain)p->processBlock(b,midi);for(int j=0;j<256;++j){float x=b.getSample(0,j);needQuiet(std::isfinite(x)&&std::abs(x)<=1,"Chain invalid");total+=double(x)*x;}}need(total>1,"Seven-plugin chain produces usable audio");need(chain[3]->correlation.load()>-.1f,"Default imaging remains mono compatible");
 BundleProcessor limiter(6);param(limiter,"drive",18);limiter.prepareToPlay(48000,256);juce::dsp::Oversampling<float> referenceTP(2,3,juce::dsp::Oversampling<float>::filterHalfBandFIREquiripple,true,true);referenceTP.initProcessing(256);float measured=0;std::mt19937 rng(4);for(int block=0;block<240;++block){for(int j=0;j<256;++j){float t=float(block*256+j)/48000;float x=.9f*std::sin(juce::MathConstants<float>::twoPi*18750*t)+.5f*std::sin(juce::MathConstants<float>::twoPi*330*t);if(block%13==0 && j==0)x+=3;b.setSample(0,j,x);b.setSample(1,j,-x*.8f);}limiter.processBlock(b,midi);auto up=referenceTP.processSamplesUp(juce::dsp::AudioBlock<float>(b));for(size_t c=0;c<2;++c)for(size_t j=0;j<up.getNumSamples();++j)measured=juce::jmax(measured,std::abs(up.getSample(c,j)));}std::cout<<"INDEPENDENT 8x TRUE PEAK "<<mv3::db(measured)<<" dBTP\n";need(mv3::db(measured)<=-.2f,"Limiter respects -0.3 dBTP within 0.1 dB tolerance on HF and impulse stress");
 mv3::Loudness meter;meter.prepare(48000);for(int n=0;n<48000*4;++n){float x=.1f*std::sin(juce::MathConstants<float>::twoPi*1000*n/48000);meter.tick(x,x);}std::cout<<"K-WEIGHTED 1kHz stereo "<<meter.integrated<<" LUFS\n";need(std::abs(meter.integrated+20)<.5f,"K-weighted stereo reference loudness correct");
 // Spectral attenuation must reduce quiet broadband noise at a given floor.
 BundleProcessor cleaner(0);param(cleaner,"floor",-40);param(cleaner,"noise",18);param(cleaner,"ess",0);param(cleaner,"thump",0);param(cleaner,"click",0);cleaner.prepareToPlay(48000,256);double before=0,after=0;std::uniform_real_distribution<float> random(-.003f,.003f);for(int block=0;block<100;++block){for(int j=0;j<256;++j){float x=random(rng);before+=double(x)*x;b.setSample(0,j,x);b.setSample(1,j,x);}cleaner.processBlock(b,midi);for(int j=0;j<256;++j)after+=double(b.getSample(0,j))*b.getSample(0,j);}need(after<before*.65,"Spectral cleanup reduces noise energy");
 BundleProcessor essDry(0),essWet(0);for(auto* p:{&essDry,&essWet}){param(*p,"noise",0);param(*p,"thump",0);param(*p,"click",0);param(*p,"essHz",7200);}param(essDry,"ess",0);param(essWet,"ess",4);essDry.prepareToPlay(48000,256);essWet.prepareToPlay(48000,256);auto dryEss=render(essDry,24000,7200,.15f),wetEss=render(essWet,24000,7200,.15f);float reduction=float(20*std::log10(rms(wetEss)/rms(dryEss)));std::cout<<"SIBILANCE REDUCTION "<<reduction<<" dB\n";need(reduction < -2.5f && reduction > -5.5f,"De-esser reaches meaningful 4 dB band attenuation");
 // Check the new leveller from its input/output behaviour, independently of
 // its implementation. A 12 dB source-level jump must become less than 10 dB.
 for(int profile=1;profile<=2;++profile){BundleProcessor low(1),high(1);for(auto* p:{&low,&high}){param(*p,"focus",0);param(*p,"micProfile",float(profile));param(*p,"room",0);param(*p,"compress",65);p->prepareToPlay(48000,256);}auto a=render(low,48000,225,.035f),c=render(high,48000,225,.14f);float jump=float(20*std::log10(rms(c)/rms(a)));std::cout<<"VOCAL PROFILE "<<profile<<" LEVEL JUMP "<<jump<<" dB\n";need(jump<10 && jump>1,"Optical vocal profile reduces level jumps without flattening voice");need(high.grDb.load()>1,"Vocal gain reduction meter responds");juce::MemoryBlock saved;high.getStateInformation(saved);BundleProcessor restored(1);restored.setStateInformation(saved.getData(),int(saved.getSize()));need(int(restored.apvts.getRawParameterValue("micProfile")->load())==profile,"Timbre profile survives state restore");}
 BundleProcessor legacyVocal(1);auto legacyState=legacyVocal.apvts.copyState();auto profileNode=legacyState.getChildWithProperty("id","micProfile");legacyState.removeChild(profileNode,nullptr);for(auto id:{"focus","match"})legacyState.removeChild(legacyState.getChildWithProperty("id",id),nullptr);legacyState.setProperty("kind",1,nullptr);legacyState.setProperty("program",0,nullptr);juce::MemoryBlock legacyBytes;if(auto xml=legacyState.createXml())juce::AudioProcessor::copyXmlToBinary(*xml,legacyBytes);legacyVocal.setStateInformation(legacyBytes.getData(),int(legacyBytes.getSize()));need(legacyVocal.apvts.getRawParameterValue("micProfile")->load()==0,"Existing 3.0 vocal state retains original engine");
 need(legacyVocal.apvts.getRawParameterValue("focus")->load()==0,"Existing vocal state retains classic processing");
 BundleProcessor fresh(1);need(fresh.getCurrentProgram()==7 && fresh.apvts.getRawParameterValue("focus")->load()==1,"New Vocal opens Signature U87 in Focus mode");fresh.setCurrentProgram(10);juce::MemoryBlock newer;fresh.getStateInformation(newer);BundleProcessor resumed(1);resumed.setStateInformation(newer.getData(),int(newer.getSize()));need(resumed.getCurrentProgram()==10 && resumed.apvts.getRawParameterValue("focus")->load()==1,"New presets and Focus state round-trip");fresh.setCurrentProgram(1);need(fresh.apvts.getRawParameterValue("focus")->load()==0,"Original presets recall classic mode");
 std::cout<<"ALL BUNDLE CHECKS PASSED\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
