#include "Processor.h"
#include "Editor.h"
juce::AudioProcessorValueTreeState::ParameterLayout BundleProcessor::layout(int k){juce::AudioProcessorValueTreeState::ParameterLayout result;for(const auto& c:mv3::products[size_t(k)].controls)result.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID(c.id,1),c.label,juce::NormalisableRange<float>(c.min,c.max,c.step),c.def));result.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID("input",1),"Entrada dB",-18.f,18.f,0.f));result.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID("output",1),"Saida dB",-18.f,k==6?0.f:6.f,0.f));if(k==1)result.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID("micProfile",1),"Timbre Metta",juce::StringArray{"Original 3.0","Corpo 87","Tubo 12"},1));result.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID("bypass",1),"Bypass",false));if(k==1){result.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID("focus",1),"Motor FOCUS",true));result.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID("match",1),"Comparacao com volume compensado",false));}return result;}
BundleProcessor::BundleProcessor(int k):AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),apvts(*this,nullptr,"MV3_STATE",layout(k)),kind(k){for(size_t i=0;i<8;++i)params[i]=apvts.getRawParameterValue(product().controls[i].id);in=apvts.getRawParameterValue("input");out=apvts.getRawParameterValue("output");bypassParameter=apvts.getRawParameterValue("bypass");micProfile=apvts.getRawParameterValue("micProfile");focusParameter=apvts.getRawParameterValue("focus");matchParameter=apvts.getRawParameterValue("match");if(kind==1)setCurrentProgram(7);}
bool BundleProcessor::isBusesLayoutSupported(const BusesLayout& b)const {auto s=b.getMainOutputChannelSet();return (s==juce::AudioChannelSet::mono()||s==juce::AudioChannelSet::stereo())&&b.getMainInputChannelSet()==s;}
std::array<float,8> BundleProcessor::values()const{std::array<float,8> result;for(size_t i=0;i<8;++i)result[i]=params[i]->load();return result;}
void BundleProcessor::prepareToPlay(double sr,int n){rate=sr;maximum=juce::jmax(32,n);factor=(kind==0||kind==4)?1:4;work.setSize(2,maximum);dry.setSize(2,maximum);os.reset();if(factor>1){os=std::make_unique<juce::dsp::Oversampling<float>>(2,2,juce::dsp::Oversampling<float>::filterHalfBandFIREquiripple,true,true);os->initProcessing(size_t(maximum));os->reset();}engine.setFocusEnabled(focusParameter && focusParameter->load()>.5f);engine.setVocalProfile(micProfile?int(micProfile->load()):0);engine.prepare(kind,rate*factor,int(maximum*factor),values());latency=os?int(std::round(os->getLatencyInSamples())):0;if(kind==0)latency+=513;if(kind==6)latency+=int(std::round(engine.lookSamples/factor));setLatencySamples(latency);dryDelay.prepare(rate,.2);tp=std::make_unique<juce::dsp::Oversampling<float>>(2,3,juce::dsp::Oversampling<float>::filterHalfBandFIREquiripple,true,true);tp->initProcessing(size_t(maximum));tp->reset();loudness.prepare(rate);inputGain.reset(rate,.025);outputGain.reset(rate,.025);active.reset(rate,.01);autoLevel.reset(rate,.75);inputGain.setCurrentAndTargetValue(mv3::gain(in->load()));outputGain.setCurrentAndTargetValue(kind==6?juce::jmin(1.f,mv3::gain(out->load())):mv3::gain(out->load()));active.setCurrentAndTargetValue(bypassParameter->load()>.5f?0:1);autoLevel.setCurrentAndTargetValue(1);matchInPower=matchOutPower=0;matchGain.reset(rate,.5);matchGain.setCurrentAndTargetValue(1);}
void BundleProcessor::setCurrentProgram(int index){index=juce::jlimit(0,getNumPrograms()-1,index);if(focusParameter)apvts.getParameter("focus")->setValueNotifyingHost(index>=7?1.f:0.f);program.store(index);if(micProfile){const int profile=index==2||index==3||index==6||index==9?2:1;auto* a=apvts.getParameter("micProfile");a->setValueNotifyingHost(a->convertTo0to1(float(profile)));}for(size_t i=0;i<8;++i){auto* p=apvts.getParameter(product().controls[i].id);const float value=index>=7?mv3::focusPresets[size_t(index-7)].values[i]:index?product().presets[size_t(index-1)].values[i]:product().controls[i].def;p->setValueNotifyingHost(p->convertTo0to1(value));}apvts.getParameter("input")->setValueNotifyingHost(apvts.getParameter("input")->convertTo0to1(index>=7?-6.f:0.f));apvts.getParameter("output")->setValueNotifyingHost(apvts.getParameter("output")->convertTo0to1(0));}
const juce::String BundleProcessor::getProgramName(int i){return kind==1 && i>=7 && i<11?juce::String(mv3::focusPresets[size_t(i-7)].name):i==0?"Default":juce::isPositiveAndBelow(i,7)?juce::String(product().presets[size_t(i-1)].name):juce::String();}
void BundleProcessor::getStateInformation(juce::MemoryBlock& b){auto s=apvts.copyState();s.setProperty("kind",kind,nullptr);s.setProperty("program",program.load(),nullptr);if(auto xml=s.createXml())copyXmlToBinary(*xml,b);}
void BundleProcessor::setStateInformation(const void* data,int size){if(auto xml=getXmlFromBinary(data,size)){if(xml->hasTagName(apvts.state.getType())){auto s=juce::ValueTree::fromXml(*xml);if(int(s.getProperty("kind",-1))==kind){program.store(juce::jlimit(0,getNumPrograms()-1,int(s.getProperty("program",0))));if(kind==1 && !s.getChildWithProperty("id","micProfile").isValid()){juce::ValueTree profile("PARAM");profile.setProperty("id","micProfile",nullptr);profile.setProperty("value",0,nullptr);s.addChild(profile,-1,nullptr);}if(kind==1){for(auto id:{"focus","match"})if(!s.getChildWithProperty("id",id).isValid()){juce::ValueTree node("PARAM");node.setProperty("id",id,nullptr);node.setProperty("value",0,nullptr);s.addChild(node,-1,nullptr);}}apvts.replaceState(s);}}}}
void BundleProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer&){run(b,false);}
void BundleProcessor::processBlockBypassed(juce::AudioBuffer<float>& b,juce::MidiBuffer&){run(b,true);}
void BundleProcessor::run(juce::AudioBuffer<float>& buffer,bool hostBypass){juce::ScopedNoDenormals guard;const int channels=buffer.getNumChannels();if(channels<1||maximum<1)return;auto vals=values();engine.setFocusEnabled(focusParameter && focusParameter->load()>.5f);engine.setVocalProfile(micProfile?int(micProfile->load()):0);engine.configure(vals);float bpm=120;if(auto* ph=getPlayHead())if(auto pos=ph->getPosition())if(auto tempo=pos->getBpm())bpm=float(*tempo);inputGain.setTargetValue(mv3::gain(in->load()));outputGain.setTargetValue(kind==6?juce::jmin(1.f,mv3::gain(out->load())):mv3::gain(out->load()));active.setTargetValue(hostBypass||bypassParameter->load()>.5f?0:1);if(kind==6 && loudness.shortTerm>-60){const float target=juce::jlimit(-12.f,12.f,vals[3]-loudness.shortTerm);autoLevel.setTargetValue(mv3::gain(target*vals[4]*.01f));}else autoLevel.setTargetValue(1);
 double inputPower=0,powerL=0,powerR=0,crossPower=0;float peak=0;
 for(int offset=0;offset<buffer.getNumSamples();offset+=maximum){const int n=juce::jmin(maximum,buffer.getNumSamples()-offset);
  for(int j=0;j<n;++j){float x=mv3::finite(buffer.getSample(0,offset+j)),y=mv3::finite(buffer.getSample(channels>1?1:0,offset+j));inputPower+=(double(x)*x+double(y)*y)*.5;float g=inputGain.getNextValue()*autoLevel.getNextValue();dry.setSample(0,j,latency?dryDelay.read(0,float(latency)):x);dry.setSample(1,j,latency?dryDelay.read(1,float(latency)):y);dryDelay.push(x,y);work.setSample(0,j,x*g);work.setSample(1,j,y*g);}
  juce::dsp::AudioBlock<float> block(work);auto view=block.getSubBlock(0,size_t(n));auto up=os?os->processSamplesUp(view):view;
  for(size_t j=0;j<up.getNumSamples();++j){float l=up.getSample(0,j),r=up.getSample(1,j);engine.process(l,r,bpm);up.setSample(0,j,l);up.setSample(1,j,r);}if(os)os->processSamplesDown(view);
  for(int j=0;j<n;++j){float a=active.getNextValue(),o=outputGain.getNextValue();float l=work.getSample(0,j)*o,r=work.getSample(1,j)*o;float dl=dry.getSample(0,j),dr=dry.getSample(1,j);if(kind==1){const float c=float(1-std::exp(-1/(rate*.6)));matchInPower+=(.5f*(dl*dl+dr*dr)-matchInPower)*c;matchOutPower+=(.5f*(l*l+r*r)-matchOutPower)*c;if(matchParameter->load()>.5f){if(matchInPower>mv3::gain(-45)*mv3::gain(-45) && matchOutPower>1.e-8f && (j&31)==0)matchGain.setTargetValue(juce::jlimit(mv3::gain(-9),mv3::gain(9),std::sqrt(matchInPower/matchOutPower)));}else matchGain.setTargetValue(1);const float g=matchGain.getNextValue();l*=g;r*=g;}if(kind==0){float mix=vals[7]*.01f;l=dl*(1-mix)+l*mix;r=dr*(1-mix)+r*mix;}l=dl*(1-a)+l*a;r=dr*(1-a)+r*a;if(channels==1)l=r=(l+r)*.5f;buffer.setSample(0,offset+j,l);if(channels>1)buffer.setSample(1,offset+j,r);work.setSample(0,j,l);work.setSample(1,j,r);powerL+=double(l)*l;powerR+=double(r)*r;crossPower+=double(l)*r;if(kind==6)loudness.tick(l,channels==1?0:r);}
  auto oversampled=tp->processSamplesUp(view);for(size_t j=0;j<oversampled.getNumSamples();++j)for(size_t c=0;c<2;++c)peak=juce::jmax(peak,std::abs(oversampled.getSample(c,j)));
 }
 const double total=juce::jmax(1,buffer.getNumSamples());inputDb.store(mv3::db(float(std::sqrt(inputPower/total))));leftDb.store(mv3::db(float(std::sqrt(powerL/total))));rightDb.store(mv3::db(float(std::sqrt(powerR/total))));correlation.store(float(crossPower/std::sqrt(juce::jmax(1.e-20,powerL*powerR))));grDb.store(engine.grDb);duck.store(engine.wetDuck);lufsM.store(loudness.momentary);lufsS.store(loudness.shortTerm);lufsI.store(loudness.integrated);tpDb.store(mv3::db(peak));
}
juce::AudioProcessorEditor* BundleProcessor::createEditor(){return new BundleEditor(*this);}
